import React, { Fragment } from 'react'
import {
  StyleSheet,
  Image,
  View,
  TouchableOpacity,
  FlatList,
  ScrollView, Text
} from 'react-native'
import { connect } from 'react-redux';
import { Icon } from 'react-native-elements'
import CustomHeader from '../Component/header'
import { pinkColor } from '../Constant';
let PrivacyPolicy = [{
  heading: "Your privacy",
  description: "BlogStar platform meets all legal requirements to protect your privacy. BlogStar privacy policy is a legal statement that explains how we can collect information about you, how we can share your information and how you can limit the sharing of your data. You will see terms written in our Privacy Policy. These terms have meanings as stated in the Definitions section below."
},
{
  heading: "Definitions",
  list: [
    'Personal data: personal data means data about a living person that can be identified from that data (or from that and other information that is in our possession or that is likely to come into our possession).',
    'Usage data: Usage data is data that is automatically collected, either generated by the use of the service or from the Service infrastructure itself (for example, the duration of a page visit).',
    "Cookies: Cookies are small pieces of data that are stored on a user's device.",
    "Data manager: data manager: a natural person or legal person who (alone or together or with other persons) determines for which purposes and in which way personal data is or will be processed. For the use of this privacy policy, we are a data manager of your data.",
    "Data processors (or service providers): data processor (or service provider): any natural or legal person who processes the data on behalf of the data manager. We can use the services of different service providers to process your data more effectively.",
    "Data Subject: Data Subject is a living person who is the subject of Personal Information.",
    "User: the user is the person who uses our service. The user agrees with the data holder, who is the subject of personal data.",
  ]
},
{
  heading: "Collect and use information",
  description: "We collect different types of information for various purposes to deliver and improve our service to you.",
  list: [
    `To offer and maintain our service`,
    `To notify our users of any changes to our service`,
    `To allow you to participate in interactive functions of our service when you choose`,
    `To provide customer support`,
    `Analyze or collect valuable information so we can improve our service`,
    `To monitor the use of our service`,
    `Detect, prevent and remedy technical problems`,
    `To provide our users with news, special offers and general information about other goods, services and events that we offer that are similar to the ones you have already purchased or are asking for unless you have chosen not to provide such information.`
  ]
},
{
  heading: "Use of data",
  description: "We use the collected data for different purposes",
  list: [
    {
      heading: "Types of data collected",
    },
    [
      {
        heading: 'Personal information',
        description: `While using BlogStar platform, we may ask you to provide us with precise, personally identifiable information that may be used to contact you or identify you ("Personal Information"). Personally, identifiable information may include but is not limited to: email address, name, address, state, province, zip code, city, cookies, and usage data.
BlogStar may use your personal information to contact you with newsletters, marketing or promotional material and other information that may be of interest to you. You can unsubscribe from receiving any or all of these messages from us by following the unsubscribe link or the instructions in the email we send.`
      },
      {
        heading: 'Usage data',
        description: `We may also collect information about how the service is used and used ("Usage Data"). This Usage Data may contain information such as the Internet Protocol address of your computer (e.g., IP address), browser type, browser version, the pages of our service you visit, the time and date of your visit, the time spent on those pages has been paid, unique device IDs and other diagnostic information.`
      },
      {
        heading: 'Tracking & cookies data',
        description: `We use cookies and similar tracking technologies to track the activity on our service and to store certain information.
Cookies are files with a small amount of data that may contain a unique anonymous identifier. Cookies are sent from a website to your browser and stored on your device. Tracking technologies that are also used are beacons, tags, and scripts to collect and track information and to improve and analyze our service.
You can instruct your browser to reject all cookies or to indicate when a cookie is being sent. However, if you do not want cookies, you may not be able to use some parts of our service.
Examples of cookies we use: session cookies (we use these cookies to use our service) and preferred cookies (we use these cookies to remember your preferences and various settings)`
      },
    ]
  ]
},
{
  heading: "Retention of data",
  description: `We only keep your data for as long as necessary for the purposes set out in this privacy policy. We will store and use your personal information to the extent required to meet our legal obligations (for example, if we are required to store your data to comply with applicable law), resolve disputes, and enforce our legal agreements and policies.
We also keep user data for internal analysis purposes. Usage data is generally retained for a shorter time, except when this data is used to enhance security or to improve the functionality of our service, or we are legally required to keep this data for a more extended time.`,
},
{
  heading: "Transfer of data",
  description: `We will take all steps reasonably necessary to ensure that your data is treated securely and following this privacy policy and that no transfer of your data to an organization or country takes place unless there are adequate controls, including the security of your data and other personal information.
Your consent to this Privacy Policy, followed by your submission of such information, indicates that you agree to that transfer.`,
},
{
  heading: "Disclosure of data",
  list: [
    `Business transaction. If we are involved in a merger, acquisition, or sale of assets, your personal information may be transferred. We will notify you before your personal information is transferred and is subject to a different privacy policy.`,
    `Disclosure for law enforcement. In certain circumstances, we may be asked to disclose your personal information if required to do so by law or as a result of valid requests from government agencies (for example, a court or government agency).`
  ]
},
{
  heading: "Data security",
  description: `The security of your data is important to us, but remember that no method of transmission via the internet or electronic storage is 100% secure. While we strive to use commercially acceptable means to guide your personal information, we cannot guarantee its absolute security.`
},
{
  heading: `Legal basis for the processing of personal data under the General Data Protection Regulation (GDPR)`,
  description: `The legal basis for filing the claim to collect and use the personal information described in this privacy policy depends on the personal information we collect and the specific context in which we collect it.`,
  list: [
    {
      heading: "Terms Feed can process your data because:",
    },
    [
      `We must conclude a contract with you`,
      `You have permitted us to do this`,
      `The processing is in our legitimate interests, and your rights do not overwrite it`,
      `For payment processing purposes`,
      `To comply with the law`
    ]
  ]
},
{
  heading: `Your data protection rights under the 2019 General Data Protection Regulation (GDPR)`,
  description: `Terms Feed aims to take reasonable steps to have you correct, change, delete, or limit the use of your data.
If you want to be kept informed of the personal information, we have about you, and if you want it to be removed from our systems, please contact us.`,
  list: [
    {
      heading: "In some cases, you have the following data protection rights",
    },
    [
      `The right to access, update, or delete the information we have about you.`,
      `The right to rectification. You have the right to have your information corrected if that information is incorrect or incomplete.`,
      `The right to object. You are permit to object to our processing of your data.`,
      `The right to restriction. You have the right to request that we limit the processing of your personal information.`,
      `The right to data portability. You are entitled to a copy of your data in a structured, machine-readable, and commonly used format`,
      `The right to withdraw permission. You also have the right to withdraw your consent at any time if Terms Feed has relied on your consent to process your personal information.`
    ]
  ],
  lastLines: `Please have it in mind that we may ask you to verify your identity before responding to such requests.
You have the right to make a complaint to a data protection authority about our collection and use of your personal information.`
},
{
  heading: "Service providers",
  description: `We may engage third-party companies and individuals to facilitate our service ("Service Providers"), provide the service on our behalf, provide service-related services, or help us analyze how our service is used.
These third parties only have access to your data to perform these tasks on our behalf and are required not to disclose them or use them for other purposes.
Analytics We may use external service providers to monitor and analyze the use of our service.`
},
{
  heading: `Google Analytics`,
  description: `Google Analytics is described as a web analysis service that is offered by Google and that tracks and reports website traffic. Google uses the collected data to track and monitor the use of our service. This data is shared with other Google services. Google may use the collected data to place and personalize the advertisements of its advertising network.
You can choose not to make your activity on the service available for Google Analytics by installing the opt-out browser add-on from Google Analytics. The plug-in prevents Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about the activity of visits.
Visit the Google Privacy & Terms web page for more information about Google's privacy practices: http://www.google.com/intl/en/policies/privacy/
  `
},
{
  heading: `Links to other sites`,
  description: `Our service may contain links to other websites that are not managed by us. If you click on a third-party link, you will be taken to that third party's site. We strongly recommend that you view the Privacy Policy of each website you visit.
We have no control over and assume no responsibility for the content, privacy policies, or practices of third-party sites or services.`
},
{
  heading: `Children's privacy`,
  description: `Our service does not apply to persons younger than 18 ('children').
We do not intentionally collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and noticed that your children have provided us with personal information, please contact us. If we become aware that we have collected personal data from children without verifying parental consent, we will take steps to remove that information from our servers.`
},
{
  heading: `Changes to this privacy policy`,
  description: `We may update/change our privacy policy from time to time. BlogStar will notify you of any changes by posting the new Privacy Policy on this page.
We will let you know via email and a prominent notice on our service before the change takes effect and update the "effective date" at the top of this Privacy Policy.
You are advised to always check this privacy policy in case of any changes
  `
},
]


class Privacy extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      category: 0
    }
  }
  static navigationOptions = {
    header: null
  }
  render() {
    const { navigation } = this.props
    let { category } = this.state
    return (
      <ScrollView stickyHeaderIndices={[0]} style={{ backgroundColor: '#323643', flex: 1, padding: 8 , }}>
        <CustomHeader navigation={navigation} title={'PRIVACY POLICY'} />
        <FlatList
          data={PrivacyPolicy}
          renderItem={({ item, index }) =>
            <View key={index} style = {{marginBottom : 12 , flex : 1}}>
              <Text style={{ marginVertical: 6, flex : 1, fontWeight: 'bold', color: '#fff', fontSize: 22 }} >{item.heading}</Text>
              <Text style={{ color: '#bbb' ,flex : 1,}} >{item.description}</Text>
              {
                item.list && item.list[0].heading ?
                  <Text style={{ marginVertical: 6, fontWeight: 'bold', color: '#fff', fontSize: 18 }} >{item.list[0].heading}</Text>
                  : null
              }
              {
                item.list && typeof (item.list[0]) === 'string' ?
                  item.list.map((text, index) =>
                    <View key={index} style={{ flexDirection: "row", flex : 1 }}>
                      <Icon name={'circle'} type={"font-awesome"} color={pinkColor} size={8}
                        containerStyle={{ marginLeft: 12, marginTop: 5 }} />
                      <Text style={{ color: '#bbb', marginHorizontal: 8 , textAlign : "justify", flex : 1, }} >{text}</Text>
                    </View>
                  )
                  : null
              }
              {
                item.list && typeof (item.list[1]) === 'object' ?
                  item.list[1].map((text, index) =>
                    text.heading ?
                      <View key={index} style={{ marginVertical: 4 }}>
                        <Text style={{ marginVertical: 6, fontWeight: 'bold', color: '#fff', fontSize: 18 }} >
                          {text.heading}</Text>
                        <View key={index} style={{ flexDirection: "row", marginVertical: 4 }}>
                          <Icon name={'circle'} type={"font-awesome"} color={pinkColor} size={8}
                            containerStyle={{ marginLeft: 12, marginTop: 5 }} />
                          <Text style={{ color: '#bbb', marginHorizontal: 8 }} >{text.description}</Text>
                        </View>
                      </View>
                      :
                      <View key={index} style={{ flexDirection: "row", marginVertical: 4 }}>
                        <Icon name={'circle'} type={"font-awesome"} color={pinkColor} size={8}
                          containerStyle={{ marginLeft: 12, marginTop: 5 }} />
                        <Text style={{ color: '#bbb', marginHorizontal: 8 }} >{text}</Text>
                      </View>
                  )
                  : null
              }
              {
                item.lastLines ?
                  <Text style={{ color : "#bbb" }} >{item.lastLines}</Text>
                  : null
              }
            </View>
          }
        />
      </ScrollView>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
})
export default Privacy
